### ISSUE TITLE
NMI sync not working correctly

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Rock#276]
> From Jon Horton

I set up 2 scheduled transactions via ACH. One on 4/27 and the other on 5/1. As of today, they're still marked pending even though both have shown up in my bank account and cleared in NMI: 

History: https://www.dropbox.com/s/x77cmudjsvj6s7p/Screenshot%202016-05-08%2008.51.30.png?dl=0
NMI: https://www.dropbox.com/s/rpncm749s6xojl8/Screenshot%202016-05-08%2008.55.08.png?dl=0

If this is happening to me, it's likely happening to others. :(

**Comment by jbaxleyiii** [comment]
*Priority* *Priority* *Priority*

Full breakdown of what is going on: 

1. Scheduled transactions are not being updated to their new status from NMI.
  - TransactionId: 1611567
  - Pending in Rock
  - Complete in NMI

2. At least one schedule somehow got its scheduleDetails removed
  - ScheduleId: 508
  - in rock UI, it shows $0.00 as the amount
  - in the db, the entire details entry is gone

3. For schedule 508, everytime the sync runs, it creates a new transaction

**Comment by dcs619** [comment]
2. Schedule details were deleted [here](https://github.com/NewSpring/Apollos/blob/master/give/observers/scheduledTransactions.js#L133).  For some reason the new TransactionDetails didn't post to Rock for ID 508 (+ 423, 1361).

3) Transactions were being duplicated because the new transaction detail (different from schedule details) wasn't being saved correctly.  Fixed [here](https://github.com/NewSpring/Rock/pull/278)
