### ISSUE TITLE
Buttons on New Communication

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#669]
The buttons for New Communication wizard are blue and need to be green.

![new_communication___rock_rms](https://user-images.githubusercontent.com/24526905/37169888-36f50590-22d7-11e8-866e-a547845f3c96.png)

**Comment by briankalwat** [comment]
@matthewalanwhite the reason this toggle is blue is because Spark has tagged that UI with the `btn-info` class – and the color associated with Info across all of Rock's UI (person notes, helper question marks, etc) is blue. I don't think it's wise for us to change that pattern. As it is now, it creates a consistent pattern across the application and also creates a distinction between info items and "primary" or "action" items that are our brand green (that generally take you to another page).
